services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=general
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build: ./
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - APP_ID=${APP_ID}
      - DOMAIN=${DOMAIN}
      - URL=${URL}
      - PREFILLED_USER_PASSWORD=${PREFILLED_USER_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - CRYPTO_SECRET=${CRYPTO_SECRET}
      - JWT_ACCESS_TIME=${JWT_ACCESS_TIME}
      - JWT_CONFIRMATION_SECRET=${JWT_CONFIRMATION_SECRET}
      - JWT_CONFIRMATION_TIME=${JWT_CONFIRMATION_TIME}
      - JWT_RESET_PASSWORD_SECRET=${JWT_RESET_PASSWORD_SECRET}
      - JWT_RESET_PASSWORD_TIME=${JWT_RESET_PASSWORD_TIME}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_TIME=${JWT_REFRESH_TIME}
      - REFRESH_COOKIE=${REFRESH_COOKIE}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - EMAIL_CLIENT_ID=${EMAIL_CLIENT_ID}
      - EMAIL_CLIENT_SECRET=${EMAIL_CLIENT_SECRET}
      - EMAIL_CLIENT_REFRESH_TOKEN=${EMAIL_CLIENT_REFRESH_TOKEN}
      - EMAIL_USER=${EMAIL_USER}
      - REDIS_URL=${REDIS_URL}
      - THROTTLE_TTL=${THROTTLE_TTL}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - TYPE=${TYPE}
      - PROJECT_ID=${PROJECT_ID}
      - PRIVATE_KEY_ID=${PRIVATE_KEY_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CLIENT_EMAIL=${CLIENT_EMAIL}
      - CLIENT_ID=${CLIENT_ID}
      - AUTH_URI=${AUTH_URI}
      - TOKEN_URI=${TOKEN_URI}
      - AUTH_PROVIDER_X509_CERT_URL=${AUTH_PROVIDER_X509_CERT_URL}
      - CLIENT_X509_CERT_URL=${CLIENT_X509_CERT_URL}
      - UNIVERSE_DOMAIN=${UNIVERSE_DOMAIN}
      - STORAGE_BUCKET=${STORAGE_BUCKET}

volumes:
  db-data:
