import Joi from 'joi';

export const validationSchema = Joi.object({
  APP_ID: Joi.string().uuid({version: 'uuidv4'}).required(),
  NODE_ENV: Joi.string().required(),
  PORT: Joi.number().required(),
  DOMAIN: Joi.string().required(),
  URL: Joi.string().uri().required(),
  DATABASE_URL: Joi.string().required(),
  REDIS_URL: Joi.string().required(),
  JWT_ACCESS_TIME: Joi.number().required(),
  JWT_CONFIRMATION_SECRET: Joi.string().required(),
  JWT_CONFIRMATION_TIME: Joi.number().required(),
  JWT_RESET_PASSWORD_SECRET: Joi.string().required(),
  JWT_RESET_PASSWORD_TIME: Joi.number().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_REFRESH_TIME: Joi.number().required(),
  REFRESH_COOKIE: Joi.string().required(),
  COOKIE_SECRET: Joi.string().required(),
  EMAIL_CLIENT_ID: Joi.string().required(),
  EMAIL_CLIENT_SECRET: Joi.string().required(),
  EMAIL_CLIENT_REFRESH_TOKEN: Joi.string().required(),
  EMAIL_USER: Joi.string().email().required(),
  THROTTLE_TTL: Joi.number().required(),
  THROTTLE_LIMIT: Joi.number().required(),
  MICROSOFT_CLIENT_ID: Joi.string().optional(),
  MICROSOFT_CLIENT_SECRET: Joi.string().optional(),
  GOOGLE_CLIENT_ID: Joi.string().optional(),
  GOOGLE_CLIENT_SECRET: Joi.string().optional(),
  FACEBOOK_CLIENT_ID: Joi.string().optional(),
  FACEBOOK_CLIENT_SECRET: Joi.string().optional(),
  GITHUB_CLIENT_ID: Joi.string().optional(),
  GITHUB_CLIENT_SECRET: Joi.string().optional(),
  // firebase config
  TYPE: Joi.string().required(),
  PROJECT_ID: Joi.string().required(),
  PRIVATE_KEY_ID: Joi.string().required(),
  PRIVATE_KEY: Joi.string().required(),
  CLIENT_EMAIL: Joi.string().required(),
  CLIENT_ID: Joi.string().required(),
  AUTH_URI: Joi.string().required(),
  TOKEN_URI: Joi.string().required(),
  AUTH_PROVIDER_X509_CERT_URL: Joi.string().required(),
  CLIENT_X509_CERT_URL: Joi.string().required(),
  UNIVERSE_DOMAIN: Joi.string().required(),
  // firebase storage
  STORAGE_BUCKET: Joi.string().required(),
});
